// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: original_click.proto

package com.mr.protobuffer;

public final class OriginalClickLog {
  private OriginalClickLog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClickLogMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string version = 1;
    /**
     * <code>optional string version = 1;</code>
     *
     * <pre>
     * 日志版本号: 1.0
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>optional string version = 1;</code>
     *
     * <pre>
     * 日志版本号: 1.0
     * </pre>
     */
    java.lang.String getVersion();
    /**
     * <code>optional string version = 1;</code>
     *
     * <pre>
     * 日志版本号: 1.0
     * </pre>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    // optional uint64 timestamp = 2;
    /**
     * <code>optional uint64 timestamp = 2;</code>
     *
     * <pre>
     * 日志写下时刻的时间戳
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>optional uint64 timestamp = 2;</code>
     *
     * <pre>
     * 日志写下时刻的时间戳
     * </pre>
     */
    long getTimestamp();

    // optional string id = 3;
    /**
     * <code>optional string id = 3;</code>
     *
     * <pre>
     * 日志 id,每一条收到的日志有一个唯一的 id
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional string id = 3;</code>
     *
     * <pre>
     * 日志 id,每一条收到的日志有一个唯一的 id
     * </pre>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 3;</code>
     *
     * <pre>
     * 日志 id,每一条收到的日志有一个唯一的 id
     * </pre>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // optional string data = 4;
    /**
     * <code>optional string data = 4;</code>
     *
     * <pre>
     * 点击参数，
     * 示 例 ：aid=xx&amp;oid=xxx&amp;cid=xxx&amp;custid=xxx&amp;sid=xxx&amp;adx_id=xxx&amp;adx_bid=xxx&amp;euid=xxx&amp;yuid=xxx&amp;dest_url=xxx
     * 具体参数描述见点击串参数说明。
     * </pre>
     */
    boolean hasData();
    /**
     * <code>optional string data = 4;</code>
     *
     * <pre>
     * 点击参数，
     * 示 例 ：aid=xx&amp;oid=xxx&amp;cid=xxx&amp;custid=xxx&amp;sid=xxx&amp;adx_id=xxx&amp;adx_bid=xxx&amp;euid=xxx&amp;yuid=xxx&amp;dest_url=xxx
     * 具体参数描述见点击串参数说明。
     * </pre>
     */
    java.lang.String getData();
    /**
     * <code>optional string data = 4;</code>
     *
     * <pre>
     * 点击参数，
     * 示 例 ：aid=xx&amp;oid=xxx&amp;cid=xxx&amp;custid=xxx&amp;sid=xxx&amp;adx_id=xxx&amp;adx_bid=xxx&amp;euid=xxx&amp;yuid=xxx&amp;dest_url=xxx
     * 具体参数描述见点击串参数说明。
     * </pre>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    // optional string user_ip = 5;
    /**
     * <code>optional string user_ip = 5;</code>
     *
     * <pre>
     * user ip
     * </pre>
     */
    boolean hasUserIp();
    /**
     * <code>optional string user_ip = 5;</code>
     *
     * <pre>
     * user ip
     * </pre>
     */
    java.lang.String getUserIp();
    /**
     * <code>optional string user_ip = 5;</code>
     *
     * <pre>
     * user ip
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserIpBytes();

    // optional string user_agent = 6;
    /**
     * <code>optional string user_agent = 6;</code>
     *
     * <pre>
     * user agent
     * </pre>
     */
    boolean hasUserAgent();
    /**
     * <code>optional string user_agent = 6;</code>
     *
     * <pre>
     * user agent
     * </pre>
     */
    java.lang.String getUserAgent();
    /**
     * <code>optional string user_agent = 6;</code>
     *
     * <pre>
     * user agent
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserAgentBytes();

    // optional string refer_url = 7;
    /**
     * <code>optional string refer_url = 7;</code>
     *
     * <pre>
     * refer url
     * </pre>
     */
    boolean hasReferUrl();
    /**
     * <code>optional string refer_url = 7;</code>
     *
     * <pre>
     * refer url
     * </pre>
     */
    java.lang.String getReferUrl();
    /**
     * <code>optional string refer_url = 7;</code>
     *
     * <pre>
     * refer url
     * </pre>
     */
    com.google.protobuf.ByteString
        getReferUrlBytes();
  }
  /**
   * Protobuf type {@code original_log.ClickLogMessage}
   */
  public static final class ClickLogMessage extends
      com.google.protobuf.GeneratedMessage
      implements ClickLogMessageOrBuilder {
    // Use ClickLogMessage.newBuilder() to construct.
    private ClickLogMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClickLogMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClickLogMessage defaultInstance;
    public static ClickLogMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ClickLogMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClickLogMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              version_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readUInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              id_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              data_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              userIp_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              userAgent_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              referUrl_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mr.protobuffer.OriginalClickLog.internal_static_original_log_ClickLogMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mr.protobuffer.OriginalClickLog.internal_static_original_log_ClickLogMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mr.protobuffer.OriginalClickLog.ClickLogMessage.class, com.mr.protobuffer.OriginalClickLog.ClickLogMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ClickLogMessage> PARSER =
        new com.google.protobuf.AbstractParser<ClickLogMessage>() {
      public ClickLogMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClickLogMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClickLogMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private java.lang.Object version_;
    /**
     * <code>optional string version = 1;</code>
     *
     * <pre>
     * 日志版本号: 1.0
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string version = 1;</code>
     *
     * <pre>
     * 日志版本号: 1.0
     * </pre>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string version = 1;</code>
     *
     * <pre>
     * 日志版本号: 1.0
     * </pre>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>optional uint64 timestamp = 2;</code>
     *
     * <pre>
     * 日志写下时刻的时间戳
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 timestamp = 2;</code>
     *
     * <pre>
     * 日志写下时刻的时间戳
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // optional string id = 3;
    public static final int ID_FIELD_NUMBER = 3;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 3;</code>
     *
     * <pre>
     * 日志 id,每一条收到的日志有一个唯一的 id
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string id = 3;</code>
     *
     * <pre>
     * 日志 id,每一条收到的日志有一个唯一的 id
     * </pre>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 3;</code>
     *
     * <pre>
     * 日志 id,每一条收到的日志有一个唯一的 id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string data = 4;
    public static final int DATA_FIELD_NUMBER = 4;
    private java.lang.Object data_;
    /**
     * <code>optional string data = 4;</code>
     *
     * <pre>
     * 点击参数，
     * 示 例 ：aid=xx&amp;oid=xxx&amp;cid=xxx&amp;custid=xxx&amp;sid=xxx&amp;adx_id=xxx&amp;adx_bid=xxx&amp;euid=xxx&amp;yuid=xxx&amp;dest_url=xxx
     * 具体参数描述见点击串参数说明。
     * </pre>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string data = 4;</code>
     *
     * <pre>
     * 点击参数，
     * 示 例 ：aid=xx&amp;oid=xxx&amp;cid=xxx&amp;custid=xxx&amp;sid=xxx&amp;adx_id=xxx&amp;adx_bid=xxx&amp;euid=xxx&amp;yuid=xxx&amp;dest_url=xxx
     * 具体参数描述见点击串参数说明。
     * </pre>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string data = 4;</code>
     *
     * <pre>
     * 点击参数，
     * 示 例 ：aid=xx&amp;oid=xxx&amp;cid=xxx&amp;custid=xxx&amp;sid=xxx&amp;adx_id=xxx&amp;adx_bid=xxx&amp;euid=xxx&amp;yuid=xxx&amp;dest_url=xxx
     * 具体参数描述见点击串参数说明。
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string user_ip = 5;
    public static final int USER_IP_FIELD_NUMBER = 5;
    private java.lang.Object userIp_;
    /**
     * <code>optional string user_ip = 5;</code>
     *
     * <pre>
     * user ip
     * </pre>
     */
    public boolean hasUserIp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string user_ip = 5;</code>
     *
     * <pre>
     * user ip
     * </pre>
     */
    public java.lang.String getUserIp() {
      java.lang.Object ref = userIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string user_ip = 5;</code>
     *
     * <pre>
     * user ip
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserIpBytes() {
      java.lang.Object ref = userIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string user_agent = 6;
    public static final int USER_AGENT_FIELD_NUMBER = 6;
    private java.lang.Object userAgent_;
    /**
     * <code>optional string user_agent = 6;</code>
     *
     * <pre>
     * user agent
     * </pre>
     */
    public boolean hasUserAgent() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string user_agent = 6;</code>
     *
     * <pre>
     * user agent
     * </pre>
     */
    public java.lang.String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userAgent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string user_agent = 6;</code>
     *
     * <pre>
     * user agent
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string refer_url = 7;
    public static final int REFER_URL_FIELD_NUMBER = 7;
    private java.lang.Object referUrl_;
    /**
     * <code>optional string refer_url = 7;</code>
     *
     * <pre>
     * refer url
     * </pre>
     */
    public boolean hasReferUrl() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string refer_url = 7;</code>
     *
     * <pre>
     * refer url
     * </pre>
     */
    public java.lang.String getReferUrl() {
      java.lang.Object ref = referUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          referUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string refer_url = 7;</code>
     *
     * <pre>
     * refer url
     * </pre>
     */
    public com.google.protobuf.ByteString
        getReferUrlBytes() {
      java.lang.Object ref = referUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        referUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      version_ = "";
      timestamp_ = 0L;
      id_ = "";
      data_ = "";
      userIp_ = "";
      userAgent_ = "";
      referUrl_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getVersionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDataBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getUserIpBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getUserAgentBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getReferUrlBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getVersionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDataBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getUserIpBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getUserAgentBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getReferUrlBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mr.protobuffer.OriginalClickLog.ClickLogMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mr.protobuffer.OriginalClickLog.ClickLogMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mr.protobuffer.OriginalClickLog.ClickLogMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mr.protobuffer.OriginalClickLog.ClickLogMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mr.protobuffer.OriginalClickLog.ClickLogMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mr.protobuffer.OriginalClickLog.ClickLogMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mr.protobuffer.OriginalClickLog.ClickLogMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mr.protobuffer.OriginalClickLog.ClickLogMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mr.protobuffer.OriginalClickLog.ClickLogMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mr.protobuffer.OriginalClickLog.ClickLogMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mr.protobuffer.OriginalClickLog.ClickLogMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code original_log.ClickLogMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mr.protobuffer.OriginalClickLog.ClickLogMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mr.protobuffer.OriginalClickLog.internal_static_original_log_ClickLogMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mr.protobuffer.OriginalClickLog.internal_static_original_log_ClickLogMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mr.protobuffer.OriginalClickLog.ClickLogMessage.class, com.mr.protobuffer.OriginalClickLog.ClickLogMessage.Builder.class);
      }

      // Construct using com.mr.protobuffer.OriginalClickLog.ClickLogMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        userIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        userAgent_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        referUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mr.protobuffer.OriginalClickLog.internal_static_original_log_ClickLogMessage_descriptor;
      }

      public com.mr.protobuffer.OriginalClickLog.ClickLogMessage getDefaultInstanceForType() {
        return com.mr.protobuffer.OriginalClickLog.ClickLogMessage.getDefaultInstance();
      }

      public com.mr.protobuffer.OriginalClickLog.ClickLogMessage build() {
        com.mr.protobuffer.OriginalClickLog.ClickLogMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mr.protobuffer.OriginalClickLog.ClickLogMessage buildPartial() {
        com.mr.protobuffer.OriginalClickLog.ClickLogMessage result = new com.mr.protobuffer.OriginalClickLog.ClickLogMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.userIp_ = userIp_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.userAgent_ = userAgent_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.referUrl_ = referUrl_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mr.protobuffer.OriginalClickLog.ClickLogMessage) {
          return mergeFrom((com.mr.protobuffer.OriginalClickLog.ClickLogMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mr.protobuffer.OriginalClickLog.ClickLogMessage other) {
        if (other == com.mr.protobuffer.OriginalClickLog.ClickLogMessage.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          bitField0_ |= 0x00000001;
          version_ = other.version_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasId()) {
          bitField0_ |= 0x00000004;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000008;
          data_ = other.data_;
          onChanged();
        }
        if (other.hasUserIp()) {
          bitField0_ |= 0x00000010;
          userIp_ = other.userIp_;
          onChanged();
        }
        if (other.hasUserAgent()) {
          bitField0_ |= 0x00000020;
          userAgent_ = other.userAgent_;
          onChanged();
        }
        if (other.hasReferUrl()) {
          bitField0_ |= 0x00000040;
          referUrl_ = other.referUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mr.protobuffer.OriginalClickLog.ClickLogMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mr.protobuffer.OriginalClickLog.ClickLogMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string version = 1;
      private java.lang.Object version_ = "";
      /**
       * <code>optional string version = 1;</code>
       *
       * <pre>
       * 日志版本号: 1.0
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string version = 1;</code>
       *
       * <pre>
       * 日志版本号: 1.0
       * </pre>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string version = 1;</code>
       *
       * <pre>
       * 日志版本号: 1.0
       * </pre>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string version = 1;</code>
       *
       * <pre>
       * 日志版本号: 1.0
       * </pre>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 1;</code>
       *
       * <pre>
       * 日志版本号: 1.0
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 1;</code>
       *
       * <pre>
       * 日志版本号: 1.0
       * </pre>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }

      // optional uint64 timestamp = 2;
      private long timestamp_ ;
      /**
       * <code>optional uint64 timestamp = 2;</code>
       *
       * <pre>
       * 日志写下时刻的时间戳
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 timestamp = 2;</code>
       *
       * <pre>
       * 日志写下时刻的时间戳
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint64 timestamp = 2;</code>
       *
       * <pre>
       * 日志写下时刻的时间戳
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 timestamp = 2;</code>
       *
       * <pre>
       * 日志写下时刻的时间戳
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // optional string id = 3;
      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 3;</code>
       *
       * <pre>
       * 日志 id,每一条收到的日志有一个唯一的 id
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string id = 3;</code>
       *
       * <pre>
       * 日志 id,每一条收到的日志有一个唯一的 id
       * </pre>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 3;</code>
       *
       * <pre>
       * 日志 id,每一条收到的日志有一个唯一的 id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 3;</code>
       *
       * <pre>
       * 日志 id,每一条收到的日志有一个唯一的 id
       * </pre>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 3;</code>
       *
       * <pre>
       * 日志 id,每一条收到的日志有一个唯一的 id
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 3;</code>
       *
       * <pre>
       * 日志 id,每一条收到的日志有一个唯一的 id
       * </pre>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        id_ = value;
        onChanged();
        return this;
      }

      // optional string data = 4;
      private java.lang.Object data_ = "";
      /**
       * <code>optional string data = 4;</code>
       *
       * <pre>
       * 点击参数，
       * 示 例 ：aid=xx&amp;oid=xxx&amp;cid=xxx&amp;custid=xxx&amp;sid=xxx&amp;adx_id=xxx&amp;adx_bid=xxx&amp;euid=xxx&amp;yuid=xxx&amp;dest_url=xxx
       * 具体参数描述见点击串参数说明。
       * </pre>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string data = 4;</code>
       *
       * <pre>
       * 点击参数，
       * 示 例 ：aid=xx&amp;oid=xxx&amp;cid=xxx&amp;custid=xxx&amp;sid=xxx&amp;adx_id=xxx&amp;adx_bid=xxx&amp;euid=xxx&amp;yuid=xxx&amp;dest_url=xxx
       * 具体参数描述见点击串参数说明。
       * </pre>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string data = 4;</code>
       *
       * <pre>
       * 点击参数，
       * 示 例 ：aid=xx&amp;oid=xxx&amp;cid=xxx&amp;custid=xxx&amp;sid=xxx&amp;adx_id=xxx&amp;adx_bid=xxx&amp;euid=xxx&amp;yuid=xxx&amp;dest_url=xxx
       * 具体参数描述见点击串参数说明。
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string data = 4;</code>
       *
       * <pre>
       * 点击参数，
       * 示 例 ：aid=xx&amp;oid=xxx&amp;cid=xxx&amp;custid=xxx&amp;sid=xxx&amp;adx_id=xxx&amp;adx_bid=xxx&amp;euid=xxx&amp;yuid=xxx&amp;dest_url=xxx
       * 具体参数描述见点击串参数说明。
       * </pre>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 4;</code>
       *
       * <pre>
       * 点击参数，
       * 示 例 ：aid=xx&amp;oid=xxx&amp;cid=xxx&amp;custid=xxx&amp;sid=xxx&amp;adx_id=xxx&amp;adx_bid=xxx&amp;euid=xxx&amp;yuid=xxx&amp;dest_url=xxx
       * 具体参数描述见点击串参数说明。
       * </pre>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 4;</code>
       *
       * <pre>
       * 点击参数，
       * 示 例 ：aid=xx&amp;oid=xxx&amp;cid=xxx&amp;custid=xxx&amp;sid=xxx&amp;adx_id=xxx&amp;adx_bid=xxx&amp;euid=xxx&amp;yuid=xxx&amp;dest_url=xxx
       * 具体参数描述见点击串参数说明。
       * </pre>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }

      // optional string user_ip = 5;
      private java.lang.Object userIp_ = "";
      /**
       * <code>optional string user_ip = 5;</code>
       *
       * <pre>
       * user ip
       * </pre>
       */
      public boolean hasUserIp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string user_ip = 5;</code>
       *
       * <pre>
       * user ip
       * </pre>
       */
      public java.lang.String getUserIp() {
        java.lang.Object ref = userIp_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string user_ip = 5;</code>
       *
       * <pre>
       * user ip
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserIpBytes() {
        java.lang.Object ref = userIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user_ip = 5;</code>
       *
       * <pre>
       * user ip
       * </pre>
       */
      public Builder setUserIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        userIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_ip = 5;</code>
       *
       * <pre>
       * user ip
       * </pre>
       */
      public Builder clearUserIp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        userIp_ = getDefaultInstance().getUserIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_ip = 5;</code>
       *
       * <pre>
       * user ip
       * </pre>
       */
      public Builder setUserIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        userIp_ = value;
        onChanged();
        return this;
      }

      // optional string user_agent = 6;
      private java.lang.Object userAgent_ = "";
      /**
       * <code>optional string user_agent = 6;</code>
       *
       * <pre>
       * user agent
       * </pre>
       */
      public boolean hasUserAgent() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string user_agent = 6;</code>
       *
       * <pre>
       * user agent
       * </pre>
       */
      public java.lang.String getUserAgent() {
        java.lang.Object ref = userAgent_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userAgent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string user_agent = 6;</code>
       *
       * <pre>
       * user agent
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserAgentBytes() {
        java.lang.Object ref = userAgent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userAgent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user_agent = 6;</code>
       *
       * <pre>
       * user agent
       * </pre>
       */
      public Builder setUserAgent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        userAgent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_agent = 6;</code>
       *
       * <pre>
       * user agent
       * </pre>
       */
      public Builder clearUserAgent() {
        bitField0_ = (bitField0_ & ~0x00000020);
        userAgent_ = getDefaultInstance().getUserAgent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_agent = 6;</code>
       *
       * <pre>
       * user agent
       * </pre>
       */
      public Builder setUserAgentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        userAgent_ = value;
        onChanged();
        return this;
      }

      // optional string refer_url = 7;
      private java.lang.Object referUrl_ = "";
      /**
       * <code>optional string refer_url = 7;</code>
       *
       * <pre>
       * refer url
       * </pre>
       */
      public boolean hasReferUrl() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string refer_url = 7;</code>
       *
       * <pre>
       * refer url
       * </pre>
       */
      public java.lang.String getReferUrl() {
        java.lang.Object ref = referUrl_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          referUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string refer_url = 7;</code>
       *
       * <pre>
       * refer url
       * </pre>
       */
      public com.google.protobuf.ByteString
          getReferUrlBytes() {
        java.lang.Object ref = referUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          referUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string refer_url = 7;</code>
       *
       * <pre>
       * refer url
       * </pre>
       */
      public Builder setReferUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        referUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string refer_url = 7;</code>
       *
       * <pre>
       * refer url
       * </pre>
       */
      public Builder clearReferUrl() {
        bitField0_ = (bitField0_ & ~0x00000040);
        referUrl_ = getDefaultInstance().getReferUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string refer_url = 7;</code>
       *
       * <pre>
       * refer url
       * </pre>
       */
      public Builder setReferUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        referUrl_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:original_log.ClickLogMessage)
    }

    static {
      defaultInstance = new ClickLogMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:original_log.ClickLogMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_original_log_ClickLogMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_original_log_ClickLogMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024original_click.proto\022\014original_log\"\207\001\n" +
      "\017ClickLogMessage\022\017\n\007version\030\001 \001(\t\022\021\n\ttim" +
      "estamp\030\002 \001(\004\022\n\n\002id\030\003 \001(\t\022\014\n\004data\030\004 \001(\t\022\017" +
      "\n\007user_ip\030\005 \001(\t\022\022\n\nuser_agent\030\006 \001(\t\022\021\n\tr" +
      "efer_url\030\007 \001(\tB&\n\022com.mr.protobufferB\020Or" +
      "iginalClickLog"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_original_log_ClickLogMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_original_log_ClickLogMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_original_log_ClickLogMessage_descriptor,
              new java.lang.String[] { "Version", "Timestamp", "Id", "Data", "UserIp", "UserAgent", "ReferUrl", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
